name: snappy
channels:
  - bioconda
  - biocore
  - conda-forge
dependencies:
  - python=3.6.7
  - snakemake=5.3.0
  - mafft=7.245
  - biopython=1.71
  - fasttree=2.1.10
  - blast=2.7.1
  - pytest=4.5.0
